### ISSUE TITLE
How to change the font for only content in posts? 

### ISSUE THREAD

**Issue by cokePanda** [nadjetey/wangana#10]
Kind of easy question, but I failed to find where to provide the source of new font  I would like to use. Any help?

thanks,

**Comment by nadjetey** [comment]
I'm sorry, I should have made it easier to alter the font. I am not very sure what you want to do with the font, but I have the site font css in a file `wangana/assets/css/_sass/_site.scss`
```css
body {
  color:#000;
  font: 17px Poly, 'Helvetica Neue', Helvetica, serif, Arial !important;
  letter-spacing: 0.001em;
}
```
I suspect that because I made the font line `!important` to override the font css from the boostrap css file, it could be the cause of your issues. Let me know if this information was helpful. Hope I helped solve your font issue
