### ISSUE TITLE
horizontal scroll-bar for code-blocks

### ISSUE THREAD

**Issue by wahani** [nadjetey/wangana#9]
Thanks for the great theme!

I have a lot of code in my blog and would like to have a horizontal scroll bar instead of automatic line breaks. However, I am not able to modify the css for `pre` to change this. What I tried is to add 

```css
pre {
overflow-x: scroll; // will add a scroll-bar but lines break anyway
white-space: nowrap; // lines still break
}
```

in the `_site.css` which has no effect. Here is an example post, which has long lines.

```md
---
layout: post
title: Test
---

{% highlight r %}
a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a
a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a = a
{% endhighlight %}
```

Do you have any idea what to do about it? I have the feeling that it has something to do with the translation and highlighting of the code not really with the css. I tried kramdown and pygments as alternative to redcarpet which did not change anything but maybe it is just some setting I am missing. 

Thanks!

**Comment by wahani** [comment]
Once I am able to ask, maybe I am also able to solve it.

Modifying the `_site.scss` won't help because `bootstrap.min.scss` will override the settings because of the order (I think) in which they are imported in `main.scss`. Adding

```css
pre code {
  white-space: pre;
}
```

at the appropriate place will solve the issue.
